### ISSUE TITLE
Build on FreeBSD 9.3 Fails with 'atomic' file not found

### ISSUE THREAD

**Issue by tuaris** [clockuniverse/terracoin#13]
Bitcoin and several other cryptos build just fine but Terracoin is failing.  Previous versions of Terracoin build without a problem.

```
/usr/local/bin/ccache clang++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -I/usr/local/include/db48/ -pthread -I/usr/local/include -I./leveldb/include -I./leveldb/helpers/memenv -I/usr/include -I/usr/include -I./secp256k1/include -I./univalue/include -Qunused-arguments -I/usr/local/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all -fPIE -O2 -pipe -fstack-protector -fno-strict-aliasing -I/usr/local/include/db48 -MT terracoind-bitcoind.o -MD -MP -MF .deps/terracoind-bitcoind.Tpo -c -o terracoind-bitcoind.o `test -f 'bitcoind.cpp' || echo './'`bitcoind.cpp
In file included from bitcoind.cpp:16:
./util.h:21:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 error generated.
gmake[2]: *** [Makefile:7496: terracoind-bitcoind.o] Error 1
gmake[2]: Leaving directory '/wrkdirs/usr/ports/net-p2p/terracoin/work/terracoin-e73a2f1/src'
gmake[1]: *** [Makefile:8446: all-recursive] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/net-p2p/terracoin/work/terracoin-e73a2f1/src'
gmake: *** [Makefile:679: all-recursive] Error 1
*** [do-build] Error code 1
```

**Comment by ahmedbodi** [comment]
Boost atomic installed?

**Comment by clockuniverse** [comment]
Did Ahmedbodi's comment help?

**Comment by tuaris** [comment]
Yes the devel/boost-libs package is installed.  It includes atomic::
https://svnweb.freebsd.org/ports/head/devel/boost-libs/pkg-plist?view=markup#l741

**Comment by clockuniverse** [comment]
Which previous versions built fine?

**Comment by tuaris** [comment]
Version 0.8.0.4
